### ISSUE TITLE
Update script to Python 3 due to change of default parser in upstream Weechat

### ISSUE THREAD

**Issue by rodneyrod** [pjz/weechat_mud#1]
EDIT: After some checking, it looks like this is a Python 2 script which will now no longer function due to Weechat changing the default Python version to 3 instead as mentioned in the blogpost below:
https://blog.weechat.org/post/2019/07/02/Python-3-by-default

Downloaded and tried to run the script, got the following error:

> 
> python: stdout/stderr (mud.py): Traceback (most recent call last):
> python: stdout/stderr (mud.py):   File "/home/weechat/.weechat/python/mud.py", line 197, in mud_command_cb
> python: stdout/stderr (mud.py):     name = mudname(args[1]) if len(args) > 1 else ''
> python: stdout/stderr (mud.py):   File "/home/weechat/.weechat/python/mud.py", line 132, in mudname
> python: stdout/stderr (mud.py):     return ''.join([c for c in name if c in string.letters + string.digits ])
> python: stdout/stderr (mud.py):   File "/home/weechat/.weechat/python/mud.py", line 132, in <listcomp>
> python: stdout/stderr (mud.py):     return ''.join([c for c in name if c in string.letters + string.digits ])
> python: stdout/stderr (mud.py): AttributeError: module 'string' has no attribute 'letters'
> python: error in function "mud_command_cb"
>

**Comment by pjz** [comment]
Oh, wow, thanks for the find.  I didn't realize they were deprecating it so soon.  I'll upgrade it when I get the chance, but no idea when that will be - I'm running on Ubuntu LTS so am still on an older version of weechat.  PRs accepted!

**Comment by rodneyrod** [comment]
Thanks for the update, not much of a python programmer myself, tried to update some of the types but that led to other errors. Might attempt again but probably won't get far myself.

**Comment by pjz** [comment]
Just did a push of a fix for that particular issue - to do full debugging myself I'll have to track down a weechat built with a python3 plugin.

**Comment by rodneyrod** [comment]
Thanks for the update, new error popped up, the plot thickens.

> python: stdout/stderr (mud.py): Traceback (most recent call last):
> python: stdout/stderr (mud.py):   File "/home/weechat/.weechat/python/mud.py", line 186, in output_cb
> python: stdout/stderr (mud.py):     MUDS[mudname].output()
> python: stdout/stderr (mud.py):   File "/home/weechat/.weechat/python/mud.py", line 110, in output
> python: stdout/stderr (mud.py):     for line in self.readlines_nb():
> python: stdout/stderr (mud.py):   File "/home/weechat/.weechat/python/mud.py", line 83, in readlines_nb
> python: stdout/stderr (mud.py):     lines, newlines = [], self._recv_nb()
> python: stdout/stderr (mud.py):   File "/home/weechat/.weechat/python/mud.py", line 64, in _recv_nb
> python: stdout/stderr (mud.py):     lines = self.s.recv(8192).split('\r\n')
> python: stdout/stderr (mud.py): TypeError: a bytes-like object is required, not 'str'

**Comment by pjz** [comment]
Ugh, I'll have to grok how their i/o model changed to handle bytes vs strings to fix this.  But my laptop runs ubuntu LTS and my server runs debian, so I don't actually have a convenient platform to test this on.  Probably I will after the next LTS is released in April, though.

**Comment by rodneyrod** [comment]
If the snap version wasn't older than the one they ship with LTS might have been an option, but it's all fine, I have workarounds so this isn't a show stopper for myself.

**Comment by pjz** [comment]
Okay, not a big deal, I just finally got around to fixing this, it should all work with py3 now.
